vim.cmd("set autoindent")
vim.cmd("set autoread")
vim.cmd("set cin")
vim.cmd("set noexpandtab")
vim.cmd("set hlsearch")
vim.cmd("set ignorecase")
vim.cmd("set incsearch")
vim.cmd("set mousehide")
vim.cmd("set noerrorbells")
vim.cmd("set noswapfile")
vim.cmd("set number")
vim.cmd("set pastetoggle=")
vim.cmd("set shiftwidth=2")
vim.cmd("set smarttab")
vim.cmd("set tabstop=2")
vim.cmd("set vb t_vb=")
vim.cmd("set relativenumber")
vim.cmd("set backspace=indent,eol,start")
vim.cmd("set clipboard=unnamed")
vim.cmd("set wrap")
vim.cmd("set guicursor=n-v-c-i:blok")
vim.g.mapleader = ' '
vim.diagnostic.config {signs=false}
